# for Python >=3.7
dist: xenial

# speed up
sudo: false

# Set the build language to Python
language: python

# Set the python version to 3.7
python: 3.7

# Install the codecov pip dependency
install:
  - pip install codecov pytest pytest-cov

# Run the unit test
script:
  - pytest --cov=./

# Push the results back to codecov
after_success:
  - codecov
